\c db_auth

CREATE TABLE IF NOT EXISTS ROLES (
    role_id INTEGER PRIMARY KEY,
    role VARCHAR(100) NOT NULL UNIQUE
);

INSERT INTO ROLES (role_id, role) VALUES (1, 'ADMIN') ON CONFLICT (role) DO NOTHING;
INSERT INTO ROLES (role_id, role) VALUES (2, 'BASIC') ON CONFLICT (role) DO NOTHING;